name: CI

on: [push, pull_request]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Cache Poetry
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies with Poetry
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi --with dev


      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Run Black (format check)
        run: poetry run black --check .

      - name: Run isort (imports check)
        run: poetry run isort --check-only .

      - name: Run Flake8 (lint)
        run: poetry run flake8 .

      - name: Run Pytest (tests)
        run: poetry run pytest --cov=app --cov-report=term-missing
